import PDFDocument from 'pdfkit';

/**
 * PDF Generator Service for Reflection Feature
 * Generates PDF documents from reflection data
 */

/**
 * Generates a PDF document from reflection data
 * @param {Object} reflection - The reflection object containing content, mood, tags, and timestamps
 * @returns {Promise<Buffer>} - PDF buffer for download
 */
export async function generateReflectionPDF(reflection) {
  return new Promise((resolve, reject) => {
    try {
      // Create a new PDF document
      const doc = new PDFDocument({
        size: 'A4',
        margins: {
          top: 50,
          bottom: 50,
          left: 50,
          right: 50
        }
      });

      // Buffer to store PDF data
      const chunks = [];
      
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err) => reject(err));

      // Add title
      doc.fontSize(24)
         .font('Helvetica-Bold')
         .text('Reflection', { align: 'center' });
      
      doc.moveDown(1);

      // Add date and time
      const formattedDate = new Date(reflection.createdAt).toLocaleString('en-US', {
        weekday: 'long',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      });
      
      doc.fontSize(12)
         .font('Helvetica')
         .text(`Date: ${formattedDate}`, { align: 'left' });
      
      doc.moveDown(0.5);

      // Add mood if present
      if (reflection.mood) {
        const moodEmojis = {
          'Happy': '😊',
          'Neutral': '😐',
          'Sad': '😢',
          'Energized': '⚡',
          'Thoughtful': '🤔'
        };
        
        const emoji = moodEmojis[reflection.mood] || '';
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .text(`Mood: ${emoji} ${reflection.mood}`, { align: 'left' });
        
        doc.moveDown(0.5);
      }

      // Add tags if present
      if (reflection.tags && reflection.tags.length > 0) {
        doc.fontSize(12)
           .font('Helvetica-Bold')
           .text('Tags: ', { continued: true })
           .font('Helvetica')
           .text(reflection.tags.join(', '));
        
        doc.moveDown(1);
      } else {
        doc.moveDown(0.5);
      }

      // Add separator line
      doc.moveTo(50, doc.y)
         .lineTo(545, doc.y)
         .stroke();
      
      doc.moveDown(1);

      // Add reflection content
      doc.fontSize(11)
         .font('Helvetica')
         .text(reflection.content, {
           align: 'left',
           lineGap: 5
         });

      // Add footer
      doc.moveDown(2);
      doc.fontSize(9)
         .font('Helvetica-Oblique')
         .text('Generated by LearnLoop Practice Tracker', {
           align: 'center'
         });

      // Finalize the PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
